# Generated by Django 2.1.2 on 2018-11-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    grade_list = [("Земля", "Земля"), ("Татуин", "Татуин"), ("Дубаи", "Дубаи")]

    operations = [
        migrations.CreateModel(
            name='candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.CharField(choices=grade_list, max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
