# Generated by Django 2.1.3 on 2018-11-15 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='candidate_answer',
        ),
        migrations.AddField(
            model_name='testanswer',
            name='candidate_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.Candidate'),
        ),
    ]
