# Generated by Django 2.1.3 on 2018-11-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20181115_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='correct_answer',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
