# Generated by Django 2.1.2 on 2018-11-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_djedai'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Answer1', models.TextField()),
                ('Answer2', models.TextField()),
                ('Answer3', models.TextField()),
                ('Answer4', models.TextField()),
                ('TrueAnswer', models.IntegerField()),
            ],
        ),
    ]
