# Generated by Django 2.1.3 on 2018-11-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_testanswer_correct_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateanswer',
            old_name='candidate_answer',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='testanswer',
            old_name='answer',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='question',
            new_name='text',
        ),
    ]
