# Generated by Django 2.1.3 on 2018-12-03 07:26

from django.db import migrations, models
import django.db.models.deletion


def rename_planet(apps, schema_editor):
    Candidate = apps.get_model('planet')
    for candidate in Candidate.objects.all():
        if candidate.planet == 'Набу':
            id_planet = 1
        elif candidate.planet == 'Татуин':
            id_planet = 2
        elif candidate.planet == 'Корусант':
            id_planet = 3
        elif candidate.planet == 'Эндор':
            id_planet = 4
        candidate.planet = id_planet
        candidate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20181122_1121'),

    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateAnswer',
            new_name='CandidateAnswers',
        ),
        migrations.RenameField(
            model_name='testanswer',
            old_name='correct_answer',
            new_name='is_correct_answer',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Planet'),
        ),
        migrations.RunPython(rename_planet, 1),
    ]
